# /*******************************************************************************
#  * Copyright 2018 Dell Inc.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author: Jim White, Dell
#  * EdgeX Foundry, Delhi, version 0.7.1
#  * added: Dec 10, 2018
#  *******************************************************************************/

version: '3.4'

volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  consul-rrp:

networks:
  edgex-network:

#################################################################
# Edgex Delhi
#################################################################
services:

  volume:
    image: edgexfoundry/docker-edgex-volume:0.6.0    
    networks:
     - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  edgex-core-consul:
    image: consul:1.1.0
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"    
    hostname: edgex-core-consul
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  edgex-core-config-seed:
    image: edgexfoundry/docker-core-config-seed-go:0.7.1    
    hostname: edgex-core-config-seed
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - edgex-core-consul

  edgex-mongo:
    image: edgexfoundry/docker-edgex-mongo:0.6.0
    ports:
      - "27017:27017"    
    hostname: edgex-mongo
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  edgex-support-logging:
    image: edgexfoundry/docker-support-logging-go:0.7.1
    ports:
      - "48061:48061"    
    hostname: edgex-support-logging
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-core-config-seed
      - edgex-mongo
      - volume

  edgex-core-metadata:
    image: edgexfoundry/docker-core-metadata-go:0.7.1
    ports:
      - "48081:48081"    
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-support-logging

  edgex-core-data:
    image: edgexfoundry/docker-core-data-go:0.7.1
    ports:
      - "48080:48080"
      - "5563:5563"    
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-support-logging

  edgex-core-command:
    image: edgexfoundry/docker-core-command-go:0.7.1
    ports:
      - "48082:48082"    
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - edgex-core-metadata
